/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiWorkspaceTreeRouteImport } from './routes/api/workspace/tree'
import { Route as ApiWorkspaceSearchRouteImport } from './routes/api/workspace/search'
import { Route as ApiWorkspaceReindexRouteImport } from './routes/api/workspace/reindex'
import { Route as ApiWorkspaceItemsRouteImport } from './routes/api/workspace/items'
import { Route as ApiWorkspaceItemRouteImport } from './routes/api/workspace/item'
import { Route as ApiWorkspaceHealthRouteImport } from './routes/api/workspace/health'
import { Route as ApiWorkspaceFileRouteImport } from './routes/api/workspace/file'
import { Route as ApiChatSettingsRouteImport } from './routes/api/chat/settings'
import { Route as ApiChatSessionsRouteImport } from './routes/api/chat/sessions'
import { Route as ApiChatSessionRouteImport } from './routes/api/chat/session'
import { Route as ApiChatRunsRouteImport } from './routes/api/chat/runs'
import { Route as ApiChatRunRouteImport } from './routes/api/chat/run'
import { Route as ApiChatResumeRouteImport } from './routes/api/chat/resume'
import { Route as ApiChatResourcesRouteImport } from './routes/api/chat/resources'
import { Route as ApiChatQuestionRouteImport } from './routes/api/chat/question'
import { Route as ApiChatProvenanceRouteImport } from './routes/api/chat/provenance'
import { Route as ApiChatNewRouteImport } from './routes/api/chat/new'
import { Route as ApiChatModelsRouteImport } from './routes/api/chat/models'
import { Route as ApiChatAbortRouteImport } from './routes/api/chat/abort'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkspaceTreeRoute = ApiWorkspaceTreeRouteImport.update({
  id: '/api/workspace/tree',
  path: '/api/workspace/tree',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkspaceSearchRoute = ApiWorkspaceSearchRouteImport.update({
  id: '/api/workspace/search',
  path: '/api/workspace/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkspaceReindexRoute = ApiWorkspaceReindexRouteImport.update({
  id: '/api/workspace/reindex',
  path: '/api/workspace/reindex',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkspaceItemsRoute = ApiWorkspaceItemsRouteImport.update({
  id: '/api/workspace/items',
  path: '/api/workspace/items',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkspaceItemRoute = ApiWorkspaceItemRouteImport.update({
  id: '/api/workspace/item',
  path: '/api/workspace/item',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkspaceHealthRoute = ApiWorkspaceHealthRouteImport.update({
  id: '/api/workspace/health',
  path: '/api/workspace/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkspaceFileRoute = ApiWorkspaceFileRouteImport.update({
  id: '/api/workspace/file',
  path: '/api/workspace/file',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatSettingsRoute = ApiChatSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ApiChatRoute,
} as any)
const ApiChatSessionsRoute = ApiChatSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => ApiChatRoute,
} as any)
const ApiChatSessionRoute = ApiChatSessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => ApiChatRoute,
} as any)
const ApiChatRunsRoute = ApiChatRunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => ApiChatRoute,
} as any)
const ApiChatRunRoute = ApiChatRunRouteImport.update({
  id: '/run',
  path: '/run',
  getParentRoute: () => ApiChatRoute,
} as any)
const ApiChatResumeRoute = ApiChatResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => ApiChatRoute,
} as any)
const ApiChatResourcesRoute = ApiChatResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => ApiChatRoute,
} as any)
const ApiChatQuestionRoute = ApiChatQuestionRouteImport.update({
  id: '/question',
  path: '/question',
  getParentRoute: () => ApiChatRoute,
} as any)
const ApiChatProvenanceRoute = ApiChatProvenanceRouteImport.update({
  id: '/provenance',
  path: '/provenance',
  getParentRoute: () => ApiChatRoute,
} as any)
const ApiChatNewRoute = ApiChatNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ApiChatRoute,
} as any)
const ApiChatModelsRoute = ApiChatModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => ApiChatRoute,
} as any)
const ApiChatAbortRoute = ApiChatAbortRouteImport.update({
  id: '/abort',
  path: '/abort',
  getParentRoute: () => ApiChatRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/chat/abort': typeof ApiChatAbortRoute
  '/api/chat/models': typeof ApiChatModelsRoute
  '/api/chat/new': typeof ApiChatNewRoute
  '/api/chat/provenance': typeof ApiChatProvenanceRoute
  '/api/chat/question': typeof ApiChatQuestionRoute
  '/api/chat/resources': typeof ApiChatResourcesRoute
  '/api/chat/resume': typeof ApiChatResumeRoute
  '/api/chat/run': typeof ApiChatRunRoute
  '/api/chat/runs': typeof ApiChatRunsRoute
  '/api/chat/session': typeof ApiChatSessionRoute
  '/api/chat/sessions': typeof ApiChatSessionsRoute
  '/api/chat/settings': typeof ApiChatSettingsRoute
  '/api/workspace/file': typeof ApiWorkspaceFileRoute
  '/api/workspace/health': typeof ApiWorkspaceHealthRoute
  '/api/workspace/item': typeof ApiWorkspaceItemRoute
  '/api/workspace/items': typeof ApiWorkspaceItemsRoute
  '/api/workspace/reindex': typeof ApiWorkspaceReindexRoute
  '/api/workspace/search': typeof ApiWorkspaceSearchRoute
  '/api/workspace/tree': typeof ApiWorkspaceTreeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/chat/abort': typeof ApiChatAbortRoute
  '/api/chat/models': typeof ApiChatModelsRoute
  '/api/chat/new': typeof ApiChatNewRoute
  '/api/chat/provenance': typeof ApiChatProvenanceRoute
  '/api/chat/question': typeof ApiChatQuestionRoute
  '/api/chat/resources': typeof ApiChatResourcesRoute
  '/api/chat/resume': typeof ApiChatResumeRoute
  '/api/chat/run': typeof ApiChatRunRoute
  '/api/chat/runs': typeof ApiChatRunsRoute
  '/api/chat/session': typeof ApiChatSessionRoute
  '/api/chat/sessions': typeof ApiChatSessionsRoute
  '/api/chat/settings': typeof ApiChatSettingsRoute
  '/api/workspace/file': typeof ApiWorkspaceFileRoute
  '/api/workspace/health': typeof ApiWorkspaceHealthRoute
  '/api/workspace/item': typeof ApiWorkspaceItemRoute
  '/api/workspace/items': typeof ApiWorkspaceItemsRoute
  '/api/workspace/reindex': typeof ApiWorkspaceReindexRoute
  '/api/workspace/search': typeof ApiWorkspaceSearchRoute
  '/api/workspace/tree': typeof ApiWorkspaceTreeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/chat/abort': typeof ApiChatAbortRoute
  '/api/chat/models': typeof ApiChatModelsRoute
  '/api/chat/new': typeof ApiChatNewRoute
  '/api/chat/provenance': typeof ApiChatProvenanceRoute
  '/api/chat/question': typeof ApiChatQuestionRoute
  '/api/chat/resources': typeof ApiChatResourcesRoute
  '/api/chat/resume': typeof ApiChatResumeRoute
  '/api/chat/run': typeof ApiChatRunRoute
  '/api/chat/runs': typeof ApiChatRunsRoute
  '/api/chat/session': typeof ApiChatSessionRoute
  '/api/chat/sessions': typeof ApiChatSessionsRoute
  '/api/chat/settings': typeof ApiChatSettingsRoute
  '/api/workspace/file': typeof ApiWorkspaceFileRoute
  '/api/workspace/health': typeof ApiWorkspaceHealthRoute
  '/api/workspace/item': typeof ApiWorkspaceItemRoute
  '/api/workspace/items': typeof ApiWorkspaceItemsRoute
  '/api/workspace/reindex': typeof ApiWorkspaceReindexRoute
  '/api/workspace/search': typeof ApiWorkspaceSearchRoute
  '/api/workspace/tree': typeof ApiWorkspaceTreeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/chat'
    | '/api/health'
    | '/api/chat/abort'
    | '/api/chat/models'
    | '/api/chat/new'
    | '/api/chat/provenance'
    | '/api/chat/question'
    | '/api/chat/resources'
    | '/api/chat/resume'
    | '/api/chat/run'
    | '/api/chat/runs'
    | '/api/chat/session'
    | '/api/chat/sessions'
    | '/api/chat/settings'
    | '/api/workspace/file'
    | '/api/workspace/health'
    | '/api/workspace/item'
    | '/api/workspace/items'
    | '/api/workspace/reindex'
    | '/api/workspace/search'
    | '/api/workspace/tree'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/chat'
    | '/api/health'
    | '/api/chat/abort'
    | '/api/chat/models'
    | '/api/chat/new'
    | '/api/chat/provenance'
    | '/api/chat/question'
    | '/api/chat/resources'
    | '/api/chat/resume'
    | '/api/chat/run'
    | '/api/chat/runs'
    | '/api/chat/session'
    | '/api/chat/sessions'
    | '/api/chat/settings'
    | '/api/workspace/file'
    | '/api/workspace/health'
    | '/api/workspace/item'
    | '/api/workspace/items'
    | '/api/workspace/reindex'
    | '/api/workspace/search'
    | '/api/workspace/tree'
  id:
    | '__root__'
    | '/'
    | '/api/chat'
    | '/api/health'
    | '/api/chat/abort'
    | '/api/chat/models'
    | '/api/chat/new'
    | '/api/chat/provenance'
    | '/api/chat/question'
    | '/api/chat/resources'
    | '/api/chat/resume'
    | '/api/chat/run'
    | '/api/chat/runs'
    | '/api/chat/session'
    | '/api/chat/sessions'
    | '/api/chat/settings'
    | '/api/workspace/file'
    | '/api/workspace/health'
    | '/api/workspace/item'
    | '/api/workspace/items'
    | '/api/workspace/reindex'
    | '/api/workspace/search'
    | '/api/workspace/tree'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiChatRoute: typeof ApiChatRouteWithChildren
  ApiHealthRoute: typeof ApiHealthRoute
  ApiWorkspaceFileRoute: typeof ApiWorkspaceFileRoute
  ApiWorkspaceHealthRoute: typeof ApiWorkspaceHealthRoute
  ApiWorkspaceItemRoute: typeof ApiWorkspaceItemRoute
  ApiWorkspaceItemsRoute: typeof ApiWorkspaceItemsRoute
  ApiWorkspaceReindexRoute: typeof ApiWorkspaceReindexRoute
  ApiWorkspaceSearchRoute: typeof ApiWorkspaceSearchRoute
  ApiWorkspaceTreeRoute: typeof ApiWorkspaceTreeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workspace/tree': {
      id: '/api/workspace/tree'
      path: '/api/workspace/tree'
      fullPath: '/api/workspace/tree'
      preLoaderRoute: typeof ApiWorkspaceTreeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workspace/search': {
      id: '/api/workspace/search'
      path: '/api/workspace/search'
      fullPath: '/api/workspace/search'
      preLoaderRoute: typeof ApiWorkspaceSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workspace/reindex': {
      id: '/api/workspace/reindex'
      path: '/api/workspace/reindex'
      fullPath: '/api/workspace/reindex'
      preLoaderRoute: typeof ApiWorkspaceReindexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workspace/items': {
      id: '/api/workspace/items'
      path: '/api/workspace/items'
      fullPath: '/api/workspace/items'
      preLoaderRoute: typeof ApiWorkspaceItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workspace/item': {
      id: '/api/workspace/item'
      path: '/api/workspace/item'
      fullPath: '/api/workspace/item'
      preLoaderRoute: typeof ApiWorkspaceItemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workspace/health': {
      id: '/api/workspace/health'
      path: '/api/workspace/health'
      fullPath: '/api/workspace/health'
      preLoaderRoute: typeof ApiWorkspaceHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workspace/file': {
      id: '/api/workspace/file'
      path: '/api/workspace/file'
      fullPath: '/api/workspace/file'
      preLoaderRoute: typeof ApiWorkspaceFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/settings': {
      id: '/api/chat/settings'
      path: '/settings'
      fullPath: '/api/chat/settings'
      preLoaderRoute: typeof ApiChatSettingsRouteImport
      parentRoute: typeof ApiChatRoute
    }
    '/api/chat/sessions': {
      id: '/api/chat/sessions'
      path: '/sessions'
      fullPath: '/api/chat/sessions'
      preLoaderRoute: typeof ApiChatSessionsRouteImport
      parentRoute: typeof ApiChatRoute
    }
    '/api/chat/session': {
      id: '/api/chat/session'
      path: '/session'
      fullPath: '/api/chat/session'
      preLoaderRoute: typeof ApiChatSessionRouteImport
      parentRoute: typeof ApiChatRoute
    }
    '/api/chat/runs': {
      id: '/api/chat/runs'
      path: '/runs'
      fullPath: '/api/chat/runs'
      preLoaderRoute: typeof ApiChatRunsRouteImport
      parentRoute: typeof ApiChatRoute
    }
    '/api/chat/run': {
      id: '/api/chat/run'
      path: '/run'
      fullPath: '/api/chat/run'
      preLoaderRoute: typeof ApiChatRunRouteImport
      parentRoute: typeof ApiChatRoute
    }
    '/api/chat/resume': {
      id: '/api/chat/resume'
      path: '/resume'
      fullPath: '/api/chat/resume'
      preLoaderRoute: typeof ApiChatResumeRouteImport
      parentRoute: typeof ApiChatRoute
    }
    '/api/chat/resources': {
      id: '/api/chat/resources'
      path: '/resources'
      fullPath: '/api/chat/resources'
      preLoaderRoute: typeof ApiChatResourcesRouteImport
      parentRoute: typeof ApiChatRoute
    }
    '/api/chat/question': {
      id: '/api/chat/question'
      path: '/question'
      fullPath: '/api/chat/question'
      preLoaderRoute: typeof ApiChatQuestionRouteImport
      parentRoute: typeof ApiChatRoute
    }
    '/api/chat/provenance': {
      id: '/api/chat/provenance'
      path: '/provenance'
      fullPath: '/api/chat/provenance'
      preLoaderRoute: typeof ApiChatProvenanceRouteImport
      parentRoute: typeof ApiChatRoute
    }
    '/api/chat/new': {
      id: '/api/chat/new'
      path: '/new'
      fullPath: '/api/chat/new'
      preLoaderRoute: typeof ApiChatNewRouteImport
      parentRoute: typeof ApiChatRoute
    }
    '/api/chat/models': {
      id: '/api/chat/models'
      path: '/models'
      fullPath: '/api/chat/models'
      preLoaderRoute: typeof ApiChatModelsRouteImport
      parentRoute: typeof ApiChatRoute
    }
    '/api/chat/abort': {
      id: '/api/chat/abort'
      path: '/abort'
      fullPath: '/api/chat/abort'
      preLoaderRoute: typeof ApiChatAbortRouteImport
      parentRoute: typeof ApiChatRoute
    }
  }
}

interface ApiChatRouteChildren {
  ApiChatAbortRoute: typeof ApiChatAbortRoute
  ApiChatModelsRoute: typeof ApiChatModelsRoute
  ApiChatNewRoute: typeof ApiChatNewRoute
  ApiChatProvenanceRoute: typeof ApiChatProvenanceRoute
  ApiChatQuestionRoute: typeof ApiChatQuestionRoute
  ApiChatResourcesRoute: typeof ApiChatResourcesRoute
  ApiChatResumeRoute: typeof ApiChatResumeRoute
  ApiChatRunRoute: typeof ApiChatRunRoute
  ApiChatRunsRoute: typeof ApiChatRunsRoute
  ApiChatSessionRoute: typeof ApiChatSessionRoute
  ApiChatSessionsRoute: typeof ApiChatSessionsRoute
  ApiChatSettingsRoute: typeof ApiChatSettingsRoute
}

const ApiChatRouteChildren: ApiChatRouteChildren = {
  ApiChatAbortRoute: ApiChatAbortRoute,
  ApiChatModelsRoute: ApiChatModelsRoute,
  ApiChatNewRoute: ApiChatNewRoute,
  ApiChatProvenanceRoute: ApiChatProvenanceRoute,
  ApiChatQuestionRoute: ApiChatQuestionRoute,
  ApiChatResourcesRoute: ApiChatResourcesRoute,
  ApiChatResumeRoute: ApiChatResumeRoute,
  ApiChatRunRoute: ApiChatRunRoute,
  ApiChatRunsRoute: ApiChatRunsRoute,
  ApiChatSessionRoute: ApiChatSessionRoute,
  ApiChatSessionsRoute: ApiChatSessionsRoute,
  ApiChatSettingsRoute: ApiChatSettingsRoute,
}

const ApiChatRouteWithChildren =
  ApiChatRoute._addFileChildren(ApiChatRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiChatRoute: ApiChatRouteWithChildren,
  ApiHealthRoute: ApiHealthRoute,
  ApiWorkspaceFileRoute: ApiWorkspaceFileRoute,
  ApiWorkspaceHealthRoute: ApiWorkspaceHealthRoute,
  ApiWorkspaceItemRoute: ApiWorkspaceItemRoute,
  ApiWorkspaceItemsRoute: ApiWorkspaceItemsRoute,
  ApiWorkspaceReindexRoute: ApiWorkspaceReindexRoute,
  ApiWorkspaceSearchRoute: ApiWorkspaceSearchRoute,
  ApiWorkspaceTreeRoute: ApiWorkspaceTreeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
