/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiChatSessionsRouteImport } from './routes/api/chat/sessions'
import { Route as ApiChatSessionRouteImport } from './routes/api/chat/session'
import { Route as ApiChatResumeRouteImport } from './routes/api/chat/resume'
import { Route as ApiChatResourcesRouteImport } from './routes/api/chat/resources'
import { Route as ApiChatQuestionRouteImport } from './routes/api/chat/question'
import { Route as ApiChatNewRouteImport } from './routes/api/chat/new'
import { Route as ApiChatModelsRouteImport } from './routes/api/chat/models'
import { Route as ApiChatAbortRouteImport } from './routes/api/chat/abort'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatSessionsRoute = ApiChatSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => ApiChatRoute,
} as any)
const ApiChatSessionRoute = ApiChatSessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => ApiChatRoute,
} as any)
const ApiChatResumeRoute = ApiChatResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => ApiChatRoute,
} as any)
const ApiChatResourcesRoute = ApiChatResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => ApiChatRoute,
} as any)
const ApiChatQuestionRoute = ApiChatQuestionRouteImport.update({
  id: '/question',
  path: '/question',
  getParentRoute: () => ApiChatRoute,
} as any)
const ApiChatNewRoute = ApiChatNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ApiChatRoute,
} as any)
const ApiChatModelsRoute = ApiChatModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => ApiChatRoute,
} as any)
const ApiChatAbortRoute = ApiChatAbortRouteImport.update({
  id: '/abort',
  path: '/abort',
  getParentRoute: () => ApiChatRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRouteWithChildren
  '/api/chat/abort': typeof ApiChatAbortRoute
  '/api/chat/models': typeof ApiChatModelsRoute
  '/api/chat/new': typeof ApiChatNewRoute
  '/api/chat/question': typeof ApiChatQuestionRoute
  '/api/chat/resources': typeof ApiChatResourcesRoute
  '/api/chat/resume': typeof ApiChatResumeRoute
  '/api/chat/session': typeof ApiChatSessionRoute
  '/api/chat/sessions': typeof ApiChatSessionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRouteWithChildren
  '/api/chat/abort': typeof ApiChatAbortRoute
  '/api/chat/models': typeof ApiChatModelsRoute
  '/api/chat/new': typeof ApiChatNewRoute
  '/api/chat/question': typeof ApiChatQuestionRoute
  '/api/chat/resources': typeof ApiChatResourcesRoute
  '/api/chat/resume': typeof ApiChatResumeRoute
  '/api/chat/session': typeof ApiChatSessionRoute
  '/api/chat/sessions': typeof ApiChatSessionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRouteWithChildren
  '/api/chat/abort': typeof ApiChatAbortRoute
  '/api/chat/models': typeof ApiChatModelsRoute
  '/api/chat/new': typeof ApiChatNewRoute
  '/api/chat/question': typeof ApiChatQuestionRoute
  '/api/chat/resources': typeof ApiChatResourcesRoute
  '/api/chat/resume': typeof ApiChatResumeRoute
  '/api/chat/session': typeof ApiChatSessionRoute
  '/api/chat/sessions': typeof ApiChatSessionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/chat'
    | '/api/chat/abort'
    | '/api/chat/models'
    | '/api/chat/new'
    | '/api/chat/question'
    | '/api/chat/resources'
    | '/api/chat/resume'
    | '/api/chat/session'
    | '/api/chat/sessions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/chat'
    | '/api/chat/abort'
    | '/api/chat/models'
    | '/api/chat/new'
    | '/api/chat/question'
    | '/api/chat/resources'
    | '/api/chat/resume'
    | '/api/chat/session'
    | '/api/chat/sessions'
  id:
    | '__root__'
    | '/'
    | '/api/chat'
    | '/api/chat/abort'
    | '/api/chat/models'
    | '/api/chat/new'
    | '/api/chat/question'
    | '/api/chat/resources'
    | '/api/chat/resume'
    | '/api/chat/session'
    | '/api/chat/sessions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiChatRoute: typeof ApiChatRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/sessions': {
      id: '/api/chat/sessions'
      path: '/sessions'
      fullPath: '/api/chat/sessions'
      preLoaderRoute: typeof ApiChatSessionsRouteImport
      parentRoute: typeof ApiChatRoute
    }
    '/api/chat/session': {
      id: '/api/chat/session'
      path: '/session'
      fullPath: '/api/chat/session'
      preLoaderRoute: typeof ApiChatSessionRouteImport
      parentRoute: typeof ApiChatRoute
    }
    '/api/chat/resume': {
      id: '/api/chat/resume'
      path: '/resume'
      fullPath: '/api/chat/resume'
      preLoaderRoute: typeof ApiChatResumeRouteImport
      parentRoute: typeof ApiChatRoute
    }
    '/api/chat/resources': {
      id: '/api/chat/resources'
      path: '/resources'
      fullPath: '/api/chat/resources'
      preLoaderRoute: typeof ApiChatResourcesRouteImport
      parentRoute: typeof ApiChatRoute
    }
    '/api/chat/question': {
      id: '/api/chat/question'
      path: '/question'
      fullPath: '/api/chat/question'
      preLoaderRoute: typeof ApiChatQuestionRouteImport
      parentRoute: typeof ApiChatRoute
    }
    '/api/chat/new': {
      id: '/api/chat/new'
      path: '/new'
      fullPath: '/api/chat/new'
      preLoaderRoute: typeof ApiChatNewRouteImport
      parentRoute: typeof ApiChatRoute
    }
    '/api/chat/models': {
      id: '/api/chat/models'
      path: '/models'
      fullPath: '/api/chat/models'
      preLoaderRoute: typeof ApiChatModelsRouteImport
      parentRoute: typeof ApiChatRoute
    }
    '/api/chat/abort': {
      id: '/api/chat/abort'
      path: '/abort'
      fullPath: '/api/chat/abort'
      preLoaderRoute: typeof ApiChatAbortRouteImport
      parentRoute: typeof ApiChatRoute
    }
  }
}

interface ApiChatRouteChildren {
  ApiChatAbortRoute: typeof ApiChatAbortRoute
  ApiChatModelsRoute: typeof ApiChatModelsRoute
  ApiChatNewRoute: typeof ApiChatNewRoute
  ApiChatQuestionRoute: typeof ApiChatQuestionRoute
  ApiChatResourcesRoute: typeof ApiChatResourcesRoute
  ApiChatResumeRoute: typeof ApiChatResumeRoute
  ApiChatSessionRoute: typeof ApiChatSessionRoute
  ApiChatSessionsRoute: typeof ApiChatSessionsRoute
}

const ApiChatRouteChildren: ApiChatRouteChildren = {
  ApiChatAbortRoute: ApiChatAbortRoute,
  ApiChatModelsRoute: ApiChatModelsRoute,
  ApiChatNewRoute: ApiChatNewRoute,
  ApiChatQuestionRoute: ApiChatQuestionRoute,
  ApiChatResourcesRoute: ApiChatResourcesRoute,
  ApiChatResumeRoute: ApiChatResumeRoute,
  ApiChatSessionRoute: ApiChatSessionRoute,
  ApiChatSessionsRoute: ApiChatSessionsRoute,
}

const ApiChatRouteWithChildren =
  ApiChatRoute._addFileChildren(ApiChatRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiChatRoute: ApiChatRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
